"""daily_bonus_log mission_points

Revision ID: 29ad3da1c7d0
Revises: 52ebf0c5fbb2
Create Date: 2026-07-04 06:18:20.135024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29ad3da1c7d0'
down_revision: Union[str, Sequence[str], None] = '52ebf0c5fbb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_bonus_log', sa.Column('mission_points', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_bonus_log', 'mission_points')
    # ### end Alembic commands ###
