"""initial schema

Revision ID: 52ebf0c5fbb2
Revises:
Create Date: 2026-07-03 14:34:46.611600

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52ebf0c5fbb2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # 추천 검색어(자동완성)용 gin_trgm_ops 인덱스의 전제. 인덱스 생성 전에 있어야 한다.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "badges",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("condition_key", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "settings",
        sa.Column(
            "id",
            sa.SmallInteger(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("streak_reset_days", sa.Integer(), nullable=True),
        sa.Column(
            "day_boundary_time", sa.Time(), server_default=sa.text("'00:00'"), nullable=False
        ),
        sa.Column("timezone", sa.Text(), server_default=sa.text("'Asia/Seoul'"), nullable=False),
        sa.CheckConstraint("id = 1", name="ck_settings_singleton"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shop_items",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=False),
        sa.Column("layer_z", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.CheckConstraint("price >= 0", name="ck_shop_price_nonneg"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("point_a", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("point_b", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("coin_balance", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("current_streak", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_complete_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('user', 'admin')", name="ck_users_role"),
        sa.CheckConstraint("coin_balance >= 0", name="ck_users_coin_nonneg"),
        sa.CheckConstraint("point_a >= 0", name="ck_users_point_a_nonneg"),
        sa.CheckConstraint("point_b >= 0", name="ck_users_point_b_nonneg"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "coin_transactions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("ref_id", sa.UUID(), nullable=True),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("reason IN ('settlement', 'withdraw')", name="ck_coin_reason"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "daily_bonus_log",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("day_bonus", sa.Integer(), nullable=False),
        sa.Column("streak_bonus", sa.Integer(), nullable=False),
        sa.Column("streak_n", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "due_date"),
    )
    op.create_table(
        "point_transactions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("ref_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('A', 'B')", name="ck_ptx_kind"),
        sa.CheckConstraint(
            "reason IN ('mission', 'mission_revoke', 'day_complete', 'day_complete_revoke', 'streak', 'streak_revoke', 'shop_purchase', 'settlement_convert')",  # noqa: E501
            name="ck_ptx_reason",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_ptx_user", "point_transactions", ["user_id", "created_at"], unique=False)
    op.create_table(
        "routines",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("repeat_type", sa.Text(), nullable=False),
        sa.Column("days_of_week", postgresql.ARRAY(sa.SmallInteger()), nullable=True),
        sa.Column("skip_holidays", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "repeat_type IN ('daily', 'weekdays', 'custom_days')", name="ck_routines_repeat_type"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "settlements",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("iso_year_week", sa.Text(), nullable=False),
        sa.Column("converted", sa.Integer(), nullable=False),
        sa.Column("carried_over", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "iso_year_week", name="uq_settlement_user_week"),
    )
    op.create_table(
        "user_badges",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("badge_id", sa.Text(), nullable=False),
        sa.Column(
            "earned_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["badge_id"],
            ["badges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "badge_id"),
    )
    op.create_table(
        "user_inventory",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("equipped", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "bought_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["shop_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "item_id", name="uq_inventory_user_item"),
    )
    op.create_index(
        "one_equipped_per_cat",
        "user_inventory",
        ["user_id", "category"],
        unique=True,
        postgresql_where=sa.text("equipped = true"),
    )
    op.create_table(
        "todos",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("routine_id", sa.UUID(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_done", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("done_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["routine_id"],
            ["routines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_todos_content_trgm",
        "todos",
        ["content"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"content": "gin_trgm_ops"},
    )
    op.create_index("idx_todos_user_date", "todos", ["user_id", "due_date"], unique=False)
    # ### end Alembic commands ###

    # settings 싱글턴 행 (id=1). 나머지 컬럼은 서버 기본값 사용.
    op.execute("INSERT INTO settings (id) VALUES (1)")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_todos_user_date", table_name="todos")
    op.drop_index(
        "idx_todos_content_trgm",
        table_name="todos",
        postgresql_using="gin",
        postgresql_ops={"content": "gin_trgm_ops"},
    )
    op.drop_table("todos")
    op.drop_index(
        "one_equipped_per_cat",
        table_name="user_inventory",
        postgresql_where=sa.text("equipped = true"),
    )
    op.drop_table("user_inventory")
    op.drop_table("user_badges")
    op.drop_table("settlements")
    op.drop_table("routines")
    op.drop_index("idx_ptx_user", table_name="point_transactions")
    op.drop_table("point_transactions")
    op.drop_table("daily_bonus_log")
    op.drop_table("coin_transactions")
    op.drop_table("users")
    op.drop_table("shop_items")
    op.drop_table("settings")
    op.drop_table("badges")
    # ### end Alembic commands ###
