"""shop_items asset_ref

Revision ID: a547e05f9f1f
Revises: 29ad3da1c7d0
Create Date: 2026-07-04 11:20:45.905478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a547e05f9f1f'
down_revision: Union[str, Sequence[str], None] = '29ad3da1c7d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_items', sa.Column('asset_ref', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_items', 'asset_ref')
    # ### end Alembic commands ###
